export const INSLAG_AANMELDEN = "INSLAG_AANMELDEN";
export const INSLAG_AFMELDEN = "INSLAG_AFMELDEN";
export const INSLAG_CHECK = "INSLAG_CHECK";
export const UITSLAG_AANMELDEN_INFO = "UITSLAG_AANMELDEN_INFO";
export const UITSLAG_AANMELDEN_ROWS = "UITSLAG_AANMELDEN_ROWS";
export const UITSLAG_AFMELDEN = "UITSLAG_AFMELDEN";
